// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_Basics_Project.Sql.Data.SQLServer.DataAccess;

namespace WEB_Basics_Project.Sql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220515114919_AddVolunteerPassword")]
    partial class AddVolunteerPassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEB_Basics_Project.Sql.Data.SQLServer.Models.Area", b =>
                {
                    b.Property<int?>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("AreaID");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("WEB_Basics_Project.Sql.Data.SQLServer.Models.Hotline", b =>
                {
                    b.Property<int?>("HotlineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AreaID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.HasKey("HotlineID");

                    b.HasIndex("AreaID");

                    b.ToTable("Hotlines");
                });

            modelBuilder.Entity("WEB_Basics_Project.Sql.Data.SQLServer.Models.Service", b =>
                {
                    b.Property<int?>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(2024)")
                        .HasMaxLength(2024);

                    b.Property<int?>("VolunteerID")
                        .HasColumnType("int");

                    b.HasKey("ServiceID");

                    b.HasIndex("VolunteerID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("WEB_Basics_Project.Sql.Data.SQLServer.Models.Volunteer", b =>
                {
                    b.Property<int?>("VolunteerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.HasKey("VolunteerID");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("WEB_Basics_Project.Sql.Data.SQLServer.Models.Hotline", b =>
                {
                    b.HasOne("WEB_Basics_Project.Sql.Data.SQLServer.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaID");
                });

            modelBuilder.Entity("WEB_Basics_Project.Sql.Data.SQLServer.Models.Service", b =>
                {
                    b.HasOne("WEB_Basics_Project.Sql.Data.SQLServer.Models.Volunteer", "Volunteer")
                        .WithMany("Services")
                        .HasForeignKey("VolunteerID");
                });
#pragma warning restore 612, 618
        }
    }
}
